/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Doctor {
  'name' : string,
  'qualifications' : string,
  'specialty' : string,
  'schedule' : string,
}
export interface Prescription {
  'name' : string,
  'submittedAt' : bigint,
  'phone' : string,
  'medicines' : string,
}
export interface _SERVICE {
  'addDoctor' : ActorMethod<[Doctor], bigint>,
  'addPrescription' : ActorMethod<[Prescription], bigint>,
  'getBusinessHours' : ActorMethod<[], string>,
  'getDoctor' : ActorMethod<[bigint], Doctor>,
  'getDoctors' : ActorMethod<[], Array<Doctor>>,
  'getPhone1' : ActorMethod<[], string>,
  'getPhone2' : ActorMethod<[], string>,
  'getPrescriptions' : ActorMethod<[], Array<Prescription>>,
  'getUpiId' : ActorMethod<[], string>,
  'removeDoctor' : ActorMethod<[bigint], undefined>,
  'setBusinessHours' : ActorMethod<[string], undefined>,
  'setPhone1' : ActorMethod<[string], undefined>,
  'setPhone2' : ActorMethod<[string], undefined>,
  'setUpiId' : ActorMethod<[string], undefined>,
  'updateDoctor' : ActorMethod<[bigint, Doctor], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];