/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Doctor = IDL.Record({
  'name' : IDL.Text,
  'qualifications' : IDL.Text,
  'specialty' : IDL.Text,
  'schedule' : IDL.Text,
});
export const Prescription = IDL.Record({
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'phone' : IDL.Text,
  'medicines' : IDL.Text,
});

export const idlService = IDL.Service({
  'addDoctor' : IDL.Func([Doctor], [IDL.Nat], []),
  'addPrescription' : IDL.Func([Prescription], [IDL.Nat], []),
  'getBusinessHours' : IDL.Func([], [IDL.Text], ['query']),
  'getDoctor' : IDL.Func([IDL.Nat], [Doctor], ['query']),
  'getDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
  'getPhone1' : IDL.Func([], [IDL.Text], ['query']),
  'getPhone2' : IDL.Func([], [IDL.Text], ['query']),
  'getPrescriptions' : IDL.Func([], [IDL.Vec(Prescription)], ['query']),
  'getUpiId' : IDL.Func([], [IDL.Text], ['query']),
  'removeDoctor' : IDL.Func([IDL.Nat], [], []),
  'setBusinessHours' : IDL.Func([IDL.Text], [], []),
  'setPhone1' : IDL.Func([IDL.Text], [], []),
  'setPhone2' : IDL.Func([IDL.Text], [], []),
  'setUpiId' : IDL.Func([IDL.Text], [], []),
  'updateDoctor' : IDL.Func([IDL.Nat, Doctor], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Doctor = IDL.Record({
    'name' : IDL.Text,
    'qualifications' : IDL.Text,
    'specialty' : IDL.Text,
    'schedule' : IDL.Text,
  });
  const Prescription = IDL.Record({
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'phone' : IDL.Text,
    'medicines' : IDL.Text,
  });
  
  return IDL.Service({
    'addDoctor' : IDL.Func([Doctor], [IDL.Nat], []),
    'addPrescription' : IDL.Func([Prescription], [IDL.Nat], []),
    'getBusinessHours' : IDL.Func([], [IDL.Text], ['query']),
    'getDoctor' : IDL.Func([IDL.Nat], [Doctor], ['query']),
    'getDoctors' : IDL.Func([], [IDL.Vec(Doctor)], ['query']),
    'getPhone1' : IDL.Func([], [IDL.Text], ['query']),
    'getPhone2' : IDL.Func([], [IDL.Text], ['query']),
    'getPrescriptions' : IDL.Func([], [IDL.Vec(Prescription)], ['query']),
    'getUpiId' : IDL.Func([], [IDL.Text], ['query']),
    'removeDoctor' : IDL.Func([IDL.Nat], [], []),
    'setBusinessHours' : IDL.Func([IDL.Text], [], []),
    'setPhone1' : IDL.Func([IDL.Text], [], []),
    'setPhone2' : IDL.Func([IDL.Text], [], []),
    'setUpiId' : IDL.Func([IDL.Text], [], []),
    'updateDoctor' : IDL.Func([IDL.Nat, Doctor], [], []),
  });
};

export const init = ({ IDL }) => { return []; };