/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ReviewEntry {
    id: bigint;
    name: string;
    createdAt: bigint;
    comment: string;
    isVerified: boolean;
    rating: bigint;
}
export interface BlogPost {
    id: bigint;
    title: string;
    content: string;
    isPublished: boolean;
    publishedAt: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface HttpRequestResult {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface ReviewsPage {
    hasMore: boolean;
    reviews: Array<ReviewEntry>;
    totalCount: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: HttpRequestResult;
}
export interface Doctor {
    name: string;
    qualifications: string;
    specialty: string;
    schedule: string;
}
export interface Appointment {
    id: bigint;
    customerName: string;
    status: string;
    createdAt: bigint;
    preferredDate: string;
    preferredTime: string;
    phone: string;
    doctorName: string;
    reason: string;
}
export interface Prescription {
    name: string;
    submittedAt: bigint;
    phone: string;
    medicines: string;
}
export interface Review {
    id: bigint;
    name: string;
    createdAt: bigint;
    comment: string;
    rating: bigint;
}
export interface HttpHeader {
    value: string;
    name: string;
}
export interface backendInterface {
    addAppointment(customerName: string, phone: string, doctorName: string, preferredDate: string, preferredTime: string, reason: string): Promise<bigint>;
    addBlogPost(title: string, content: string): Promise<bigint>;
    addDoctor(doctor: Doctor): Promise<bigint>;
    addPrescription(prescription: Prescription): Promise<bigint>;
    addReview(name: string, rating: bigint, comment: string): Promise<bigint>;
    addUserReview(name: string, rating: bigint, comment: string): Promise<bigint>;
    askGemini(prompt: string): Promise<string>;
    deleteBlogPost(id: bigint): Promise<boolean>;
    getAllBlogPostsAdmin(): Promise<Array<BlogPost>>;
    getAppointments(): Promise<Array<Appointment>>;
    getBlogPosts(): Promise<Array<BlogPost>>;
    getBusinessHours(): Promise<string>;
    getDoctor(id: bigint): Promise<Doctor>;
    getDoctors(): Promise<Array<Doctor>>;
    getPhone1(): Promise<string>;
    getPhone2(): Promise<string>;
    getPrescriptions(): Promise<Array<Prescription>>;
    getReviews(): Promise<Array<Review>>;
    getReviewsPaginated(page: bigint, pageSize: bigint): Promise<ReviewsPage>;
    getUpiId(): Promise<string>;
    removeDoctor(id: bigint): Promise<void>;
    setBusinessHours(newBusinessHours: string): Promise<void>;
    setPhone1(newPhone1: string): Promise<void>;
    setPhone2(newPhone2: string): Promise<void>;
    setUpiId(newUpiId: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateAppointmentStatus(id: bigint, status: string): Promise<boolean>;
    updateBlogPost(id: bigint, title: string, content: string, isPublished: boolean): Promise<boolean>;
    updateDoctor(id: bigint, doctor: Doctor): Promise<void>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAppointment(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAppointment(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAppointment(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addBlogPost(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addBlogPost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBlogPost(arg0, arg1);
            return result;
        }
    }
    async addDoctor(arg0: Doctor): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDoctor(arg0);
            return result;
        }
    }
    async addPrescription(arg0: Prescription): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPrescription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPrescription(arg0);
            return result;
        }
    }
    async addReview(arg0: string, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0, arg1, arg2);
            return result;
        }
    }
    async addUserReview(arg0: string, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addUserReview(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUserReview(arg0, arg1, arg2);
            return result;
        }
    }
    async askGemini(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.askGemini(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.askGemini(arg0);
            return result;
        }
    }
    async deleteBlogPost(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return result;
        }
    }
    async getAllBlogPostsAdmin(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBlogPostsAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBlogPostsAdmin();
            return result;
        }
    }
    async getAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointments();
            return result;
        }
    }
    async getBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPosts();
            return result;
        }
    }
    async getBusinessHours(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusinessHours();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusinessHours();
            return result;
        }
    }
    async getDoctor(arg0: bigint): Promise<Doctor> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctor(arg0);
            return result;
        }
    }
    async getDoctors(): Promise<Array<Doctor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctors();
            return result;
        }
    }
    async getPhone1(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhone1();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhone1();
            return result;
        }
    }
    async getPhone2(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhone2();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhone2();
            return result;
        }
    }
    async getPrescriptions(): Promise<Array<Prescription>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrescriptions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrescriptions();
            return result;
        }
    }
    async getReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviews();
            return result;
        }
    }
    async getReviewsPaginated(arg0: bigint, arg1: bigint): Promise<ReviewsPage> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewsPaginated(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewsPaginated(arg0, arg1);
            return result;
        }
    }
    async getUpiId(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpiId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpiId();
            return result;
        }
    }
    async removeDoctor(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeDoctor(arg0);
            return result;
        }
    }
    async setBusinessHours(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setBusinessHours(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBusinessHours(arg0);
            return result;
        }
    }
    async setPhone1(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPhone1(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPhone1(arg0);
            return result;
        }
    }
    async setPhone2(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPhone2(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPhone2(arg0);
            return result;
        }
    }
    async setUpiId(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUpiId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUpiId(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateAppointmentStatus(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointmentStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointmentStatus(arg0, arg1);
            return result;
        }
    }
    async updateBlogPost(arg0: bigint, arg1: string, arg2: string, arg3: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogPost(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogPost(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateDoctor(arg0: bigint, arg1: Doctor): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDoctor(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDoctor(arg0, arg1);
            return result;
        }
    }
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
